# Generated by Django 4.2.7 on 2023-12-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('Buff', 'Buff'), ('Chicken', 'Chicken'), ('Veg', 'Veg')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
